# This file tells Netlify exactly how to build your site.

[build]
  # This is the command Netlify will run to compile your TypeScript
  command = "npm run build"
  # The directory with your website files (index.html, etc.)
  publish = "public"

[functions]
  # This tells Netlify where to find the COMPILED JavaScript functions
  directory = "dist/api"
  node_bundler = "esbuild"
