import type { Actor, Role } from "../../../src/ops/contracts/core";

const permissions: Record<Role, ReadonlySet<string>> = {
  owner: new Set([
    "session.read",
    "workspace.bootstrap",
    "workspace.list",
    "item.create",
    "identifier.add",
    "lot.create",
    "lot.allocate",
    "item.cost.correct",
    "inventory.list",
    "item.detail",
    "lot.detail",
    "scan.resolve",
    "location.list",
    "location.create",
    "location.parent",
    "location.delete",
    "item.move",
  ]),
  manager: new Set([
    "session.read",
    "item.create",
    "identifier.add",
    "lot.create",
    "lot.allocate",
    "item.cost.correct",
    "inventory.list",
    "item.detail",
    "lot.detail",
    "scan.resolve",
    "location.list",
    "location.create",
    "location.parent",
    "location.delete",
    "item.move",
  ]),
  lister: new Set([
    "session.read",
    "item.create",
    "identifier.add",
    "lot.create",
    "inventory.list",
    "item.detail",
    "lot.detail",
    "scan.resolve",
    "location.list",
  ]),
  warehouse: new Set([
    "session.read",
    "inventory.list",
    "item.detail",
    "lot.detail",
    "scan.resolve",
    "location.list",
    "location.create",
    "item.move",
  ]),
};

export function can(actor: Actor, operation: string) {
  return permissions[actor.role].has(operation);
}
