const clothingKeywords = [
  "dress",
  "shirt",
  "pants",
  "jeans",
  "skirt",
  "jacket",
  "coat",
  "sweater",
  "hoodie",
  "blouse",
  "t-shirt",
  "shorts",
  "suit",
  "cardigan",
  "scarf",
  "gloves",
  "hat",
  "beanie",
  "cap",
  "socks",
  "leggings",
  "tights",
  "swimsuit",
  "bikini",
  "lingerie",
  "underwear",
  "pajamas",
  "robe",
  "vest",
  "top",
  "tank top",
  "bodysuit",
  "kimono",
  "poncho",
  "trench coat",
  "windbreaker",
  "blazer",
  "denim jacket",
  "leather jacket",
  "peacoat",
  "parka",
  "down jacket",
  "sweatpants",
  "joggers",
  "cargo pants",
  "chinos",
  "culottes",
  "overalls",

  // french keywords
  "robe",
  "chemise",
  "pantalon",
  "jeans",
  "jupe",
  "veste",
  "manteau",
  "pull",
  "sweat à capuche",
  "blouse",
  "t-shirt",
  "shorts",
  "costume",
  "cardigan",
  "écharpe",
  "gants",
  "chapeau",
  "bonnet",
  "casquette",
  "chaussettes",
  "leggings",
  "collants",
  "maillot de bain",
  "bikini",
  "lingerie",
  "sous-vêtements",
  "pyjama",
  "robe de chambre",
  "gilet",
  "top",
  "débardeur",
  "body",
  "kimono",
  "poncho",
  "trench-coat",
  "coupe-vent",
  "blazer",
  "veste en denim",
  "veste en cuir",
  "caban",
  "parka",
  "doudoune",
  "pantalon de survêtement",
  "joggers",
  "pantalon cargo",
  "chinos",
  "culottes",
  "salopette",
  "tailleur",
  "ensemble",
  "combinaison",
  "combishort",

  // german keywords
  "kleid",
  "hemd",
  "hose",
  "jeans",
  "rock",
  "jacke",
  "mantel",
  "pullover",
  "kapuzenpullover",
  "bluse",
  "t-shirt",
  "shorts",
  "anzug",
  "cardigan",
  "schal",
  "handschuhe",
  "hut",
  "mütze",
  "kappe",
  "socken",
  "leggings",
  "strumpfhose",
  "badeanzug",
  "bikini",
  "dessous",
  "unterwäsche",
  "pyjama",
  "bademantel",
  "weste",
  "top",
  "trägerloses top",
  "body",
  "kimono",
  "poncho",
  "trenchcoat",
  "windjacke",
  "blazer",
  "jeansjacke",
  "lederjacke",
  "peacoat",
  "parka",
  "daunenjacke",
  "jogginghose",
  "joggers",
  "cargo hose",
  "chinos",
  "culottes",
  "overall",
  "anzug",
  "ensemble",
  "kombination",

  // polish
  "sukienka",
  "koszula",
  "spodnie",
  "jeans",
  "spódnica",
  "kurtka",
  "płaszcz",
  "sweter",
  "bluza z kapturem",
  "bluzka",
  "t-shirt",
  "szorty",
  "garnitur",
  "cardigan",
  "szalik",
  "rękawiczki",
  "kapelusz",
  "czapka",
  "czapka z daszkiem",
  "skarpetki",
  "legginsy",
  "rajstopy",
  "strój kąpielowy",
  "bikini",
  "bielizna",
  "piżama",
  "szlafrok",
  "kamizelka",
  "top",
  "top bez ramiączek",
  "body",
  "kimono",
  "poncho",
  "trench coat",
  "kurtka przeciwdeszczowa",
  "blazer",
  "kurtka jeansowa",
  "kurtka skórzana",
  "płaszcz dwurzędowy",
  "parka",
  "kurtka puchowa",
  "spodnie dresowe",
  "joggers",
  "spodnie cargo",
  "chinos",
  "culottes",
  "ogrodniczki",
  "garnitur",
  "komplet",
  "kombinezon",
  "kombishort",

  //   dutch

  "jurk",
  "hemd",
  "broek",
  "jeans",
  "rok",
  "jas",
  "mantel",
  "trui",
  "hoodie",
  "blouse",
  "t-shirt",
  "shorts",
  "pak",
  "cardigan",
  "sjaal",
  "handschoenen",
  "hoed",
  "muts",
  "pet",
  "sokken",
  "legging",
  "panty",
  "badpak",
  "bikini",
  "lingerie",
  "ondergoed",
  "pyjama",
  "badjas",
  "gilet",
  "top",
  "tank top",
  "body",
  "kimono",
  "poncho",
  "trenchcoat",
  "windjack",
  "blazer",
  "spijkerjack",
  "leren jas",
  "peacoat",
  "parka",
  "donsjack",
  "joggingbroek",
  "joggers",
  "cargo broek",
  "chinos",
  "culottes",
  "overall",
  "pak",
  "ensemble",
  "kombinatie",
];

// A function to detect if the item is clothing based on generated title and description
export function isClothingItem(title: string, description: string): boolean {
  const titleAndDescription = `${title} ${description}`.toLowerCase();

  return clothingKeywords.some((keyword) =>
    titleAndDescription.includes(keyword),
  );
}

// a function to return measurement advice text based on whether the item is clothing or not
export function getMeasurementAdvice(
  isClothing: boolean,
  messages: any,
): string {
  if (isClothing) {
    return messages.advice.clothing.measurements;
  }
  return "";
}
