export const languageMap: { [key: string]: string } = {
  en: "English",
  fr: "French",
  cz: "Czech",
  hr: "Croatian",
  da: "Danish",
  nl: "Dutch",
  fi: "Finnish",
  de: "German",
  el: "Greek",
  hu: "Hungarian",
  it: "Italian",
  lt: "Lithuanian",
  lv: "Latvian",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  sk: "Slovak",
  es: "Spanish",
};
