export const languageMap: { [key: string]: string } = {
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  nl: "Dutch",
  pl: "Polish",
  hu: "Hungarian",
  sk: "Slovak",
  cz: "Czech",
  lt: "Lithuanian",
  lv: "Latvian",
  ro: "Romanian",
};
