name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Lint with ESLint
      - name: Lint code
        run: npm run lint

      # 5) Type-check with tsc
      - name: Type-check
        run: npm run type-check

      # 6) Verify formatting
      - name: Format check
        run: npm run format-check

      # 7) Audit for high-severity vulns
      - name: Audit dependencies
        run: npm audit --audit-level=high

      # 8) (Optional) Run your tests, if/when you add them
      # - name: Run tests
      #   run: npm test
